### ISSUE TITLE
Nil value 'label' caused by new items being stored

### ISSUE THREAD

**Issue by Puntherline** [ESX-Org/esx_addoninventory#32]
I've been experiencing an issue where when I add a new item to any addon inventory, it will not be able to get the label of it instantly. Example: Police stock has 8 x "apple" inside it, that's it. The database will only list those 8 apples in there. You can open the menu fine, it will read everything without trouble. Once you add a new item that this inventory hasn't had yet, you can't open it again.

I have managed to close in on this bug by trial and error and it seems to be that when the resource starts, it will grab all the item names from the `addon_inventory_items` table (server\main.lua:8) and use those to grab the labels from the `items` table, problem is that if one of them doesn't exist yet it can't look up the label thus resulting in the nil value.

I think that this should be easy to fix (re-run the code starting at line 7 every time a new item is being added to the database, resource-heavy but should prevent bug) or maybe add a new column to the database where you store the label once again. Sure, more work, but it would actually work by then.

I will try to fix this by myself in the meantime, but it probably won't be a pretty fix and I will report on it later. (Small edit: [Video of me showing how to actually break it](https://www.youtube.com/watch?v=y-M5C_05Nck))

**Comment by giorgos94** [comment]
I managed to fix this issue.
I had the problem most people were facing which is that if you deposit an item that you hadn't deposited before, it's name would be "UNDEFINED" in the property's inventory and you had to ensure the resource in order to retrieve the correct name label of it.

What I did was the following:

esx_addoninventory\server\classes\addoninventory.lua

**FROM**
			name  = name,
			count = 0,
			label = items[name]

**CHANGED TO**

			name  = name,
			count = 0,
			label = Items[name]


With this change, everything is working as expected.
I know that we had to change Items to items before but this way the property inventory doesn't work as expected for me.
Are there going to be any conflicts with the change I suggested above?

**Comment by Puntherline** [comment]
@giorgos94 That did fix it. What I've tried too is to just update to the most recent version (didn't even see any major changes here on github) and that fixed everything I've mentioned above, at least for me and another server where I help out at so that most likely fully fixed it.

So for anybody stumbling upon this issue, try re-installing the most recent version.

**Comment by giorgos94** [comment]
Can you please add me on Discord mate?
I'm having a really hard time with this one.
Even though I get the item names correctly, the items do not register correct in addon_inventory_items.
With this I mean that if I store ex. 4 items like 1x bread, 1x water, 1x beer, 1x fixtool some of them will register with "count" 0 and others correctly as 1 therefore I can only see the ones with value 1

Please add me, I would like to ask you one thing about this GeorgeGR#9010

Thanks in advance!
